# JuliaのTips集
このページはJuliaでの実装におけるTips (詰まったところの解決策)をまとめたものである．体系的にまとまってはいない．

## 関数名の!記号
単なる**慣習**として関数への入力を変更する場合に!を付ける．

関数内で配列を変更する場合には注意が必要である．以下に入力された配列を同じサイズの要素1の配列で置き換える，ということを目的として書かれた2つの関数がある．違いは`v`の後に`[:]`としているかどうかである．

In [1]:
function wrong!(a::Array)
    a = ones(size(a))
end

function right!(a::Array)
    a[:] = ones(size(a))
end

right! (generic function with 1 method)

実行すると`wrong!`の場合には入力された配列が変更されていないことがわかる．

In [2]:
using Random
v = rand(2, 2)
println("v : ", v)

wrong!(v)
println("wrong : ", v)

right!(v)
println("right : ", v)

v : [0.5832535214226895 0.9863239196768177; 0.9385627748273042 0.6036749327061697]
wrong : [0.5832535214226895 0.9863239196768177; 0.9385627748273042 0.6036749327061697]
right : [1.0 1.0; 1.0 1.0]


## 配列の1次元化
配列を一次元化(flatten)する方法．まずは3次元配列を作成する．

In [3]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.171359  0.970301
 0.368827  0.400136

[:, :, 2] =
 0.415898  0.193467
 0.39925   0.588116

用意されている`flatten`を素直に用いると次のようになる．

In [4]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.17135901366980444
 0.3688271762434565
 0.9703008447114903
 0.4001358330916738
 0.41589764263469364
 0.39925026276573816
 0.19346717296946458
 0.5881157611777139

ただし，単に`B[:]`とするだけでもよい．

In [5]:
B[:]

8-element Vector{Float64}:
 0.17135901366980444
 0.3688271762434565
 0.9703008447114903
 0.4001358330916738
 0.41589764263469364
 0.39925026276573816
 0.19346717296946458
 0.5881157611777139

## 行列の行・列ごとの正規化
シミュレーションにおいてニューロン間の重み行列を行あるいは列ごとに正規化 (weight normalization)する場合がある．これは各ニューロンへの入力の大きさを同じにする働きや重みの発散を防ぐ役割がある．以下では行ごとの和を1にする．

In [6]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.89766   0.251363  0.621109
 0.584915  0.156382  0.985538
 0.288508  0.387411  0.0143406

In [7]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.506842  0.316118  0.383167
 0.330259  0.196668  0.607986
 0.162899  0.487214  0.00884685

In [8]:
println(sum(Wnormed, dims=1))

[0.9999999999999999 1.0 1.0]


## 行列の結合 (concatenate)
行列の結合はMATLABに近い形式で行うことができる．まず，2つの行列A, Bを用意する．

In [9]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

### 水平結合 (Horizontal concatenation)
`hcat`を使うやり方と，`[ ]`を使うやり方がある．

In [11]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [12]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

なお，MATLABのように次のようにすると正しく結合はされない．

In [13]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

### 垂直結合 (Vertical concatenation)

In [14]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [15]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [16]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

## 配列に新しい軸を追加
要はnumpyでの`A[None, :]`や`A[np.newaxis, :]`のようなことがしたい場合．やや面倒だが，`reshape`を使うか，`[CartesianIndex()]`を用いる．

In [17]:
v = rand(3)

3-element Vector{Float64}:
 0.29868483872953977
 0.9074295824314997
 0.7142987103485341

In [18]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.298685  0.90743  0.714299

## Array{Array{Float64, x},1}をArray{Float64, x+1}に変換
numpyでは`array([matrix for i in range()])`などを用いると，1次元配列のリストを2次元配列に変換できた．Juliaでも同様にする場合は`hcat(...)`や`cat(...)`を用いる．

In [19]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : Vector

{Vector{Float64}}
Size : (5,)


In [20]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : LinearAlgebra.Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


以下は多次元配列の場合．`cat(...)`で配列を結合し，`permitedims`で転置する．

In [21]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [22]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)


## 二項分布 (bernoulli distribution)のサンプリング

In [23]:
p = 0.7
N = 100

100

In [24]:
using BenchmarkTools

In [25]:
@benchmark floor.(p .+ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.91 KiB
  allocs estimate:  7
  --------------
  minimum time:     866.038 ns (0.00% GC)
  median time:      896.226 ns (0.00% GC)
  mean time:        967.730 ns (2.68% GC)
  maximum time:     14.879 μs (87.81% GC)
  --------------
  samples:          10000
  evals/sample:     53

In [26]:
println(sum(floor.(p .+ rand(N)) .== 1.0) / N) 

0.68


In [27]:
@benchmark 1.0f0 * (p .≥ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.55 KiB
  allocs estimate:  6
  --------------
  minimum time:     935.714 ns (0.00% GC)
  median time:      985.714 ns (0.00% GC)
  mean time:        1.068 μs (2.48% GC)
  maximum time:     33.625 μs (96.30% GC)
  --------------
  samples:          10000
  evals/sample:     28

In [28]:
println(sum(1.0f0 * (p .≥ rand(N)) .== 1.0) / N) 

0.73


## Roth's column lemma

Roth's column lemmaは，例えば，$A, B, C$が与えられていて，$X$を未知とするときの方程式 $AXB = C$を考えると，この方程式は

$$
(B^\top \otimes A)\text{vec}(X) = \text{vec}(AXB)=\text{vec}(C)
$$

の形に書き下すことができる，というものである．$\text{vec}(\cdot)$はvec作用素（行列を列ベクトル化する作用素）である．`vec(X) = vcat(X...)`で実現できる．Roth's column lemmaを用いれば，$AXB = C$の解は

$$
X = \text{vec}^{-1}\left((B^\top \otimes A)^{-1}\text{vec}(C)\right)
$$

として得られる．ただし，$\text{vec}(\cdot)^{-1}$は列ベクトルを行列に戻す作用素(inverse of the vectorization operator)である．`reshape()`で実現できる．2つの作用素をまとめると，

$$
\begin{align}
\text{vec} &: R^{m\times n}\to R^{mn}\\
\text{vec}^{−1} &: R^{mn}\to R^{m×n}
\end{align}
$$

であり，$\text{vec}^{−1}\left(\text{vec}(X)\right)=X\ (\text{for all}\ X\in R^{m\times n})，\text{vec}\left(\text{vec}^{−1}(x)\right)=x\ (\text{for all}\ x \in R^{mn})$となる．

In [29]:
using LinearAlgebra, Kronecker, Random

In [30]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [31]:
vec(X) = vcat(X...)

vec (generic function with 1 method)

In [32]:
X = reshape((B' ⊗ A) \ vec(C), (m, m))

4×4 Matrix{Float64}:
  -6.36945   -12.1054    -11.5015   -37.2391
  -7.43169   -13.7294    -12.4696   -37.2072
 -10.8617    -20.535     -19.3533   -61.7945
   0.569664    0.213792   -1.06218  -10.4073

In [33]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

## "splat" operator ... 
https://docs.julialang.org/en/v1/base/base/#...

## broadcastingの回避

In [34]:
foo(a,b) = sum(a) + b

foo (generic function with 1 method)

In [35]:
println(foo.(Ref([1,2]),[3,4,5]))
println(foo.(([1,2],), [3,4,5]))
println(foo.([[1,2]], [3,4,5]))

[6, 7, 8]
[6, 7, 8]


[6, 7, 8]


## `var`の使用

In [36]:
var"log(θ+μ)" = 10

10

## reshapeにおける残りの次元の指定
numpyにおいては(2, 3, 5)次元の配列に対し，reshape(-1, 5)を行うと(6, 5)次元の配列となった．これと同様なことは，Juliaでは:を使うことで実装できる．

In [37]:
a = rand(2,3,5)
b = reshape(a, (:, 5))

6×5 Matrix{Float64}:
 0.833379   0.506352  0.587947   0.784246  0.0260247
 0.506091   0.826972  0.279171   0.86387   0.0400987
 0.0645915  0.594297  0.126421   0.181552  0.688678
 0.287908   0.554669  0.265179   0.229792  0.311631
 0.948209   0.736961  0.0463345  0.39206   0.84656
 0.254488   0.999719  0.771749   0.868979  0.192396