# JuliaのTips集
このページはJuliaでの実装におけるTips (詰まったところの解決策)をまとめたものである．体系的にまとまってはいない．

## 関数名の!記号
単なる**慣習**として関数への入力を変更する場合に!を付ける．

関数内で配列を変更する場合には注意が必要である．以下に入力された配列を同じサイズの要素1の配列で置き換える，ということを目的として書かれた2つの関数がある．違いは`v`の後に`[:]`としているかどうかである．

In [1]:
function wrong!(a::Array)
    a = ones(size(a))
end

function right!(a::Array)
    a[:] = ones(size(a))
end

right! (generic function with 1 method)

実行すると`wrong!`の場合には入力された配列が変更されていないことがわかる．

In [2]:
using Random
v = rand(2, 2)
println("v : ", v)

wrong!(v)
println("wrong : ", v)

right!(v)
println("right : ", v)

v : 

[0.5186591134015561 0.6048708090823378; 0.238331348187236 0.20953434348009425]
wrong : [0.5186591134015561 0.6048708090823378; 0.238331348187236 0.20953434348009425]
right : [1.0 1.0; 

1.0 1.0]


## 配列の1次元化
配列を一次元化(flatten)する方法．まずは3次元配列を作成する．

In [3]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.611728  0.633953
 0.473456  0.830435

[:, :, 2] =
 0.776682  0.854543
 0.969433  0.858047

用意されている`flatten`を素直に用いると次のようになる．

In [4]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.6117275510785916
 0.4734555760000845
 0.6339529180095502
 0.830435097104653
 0.7766823530347728
 0.9694329613133161
 0.854543242553403
 0.8580472759841979

ただし，単に`B[:]`とするだけでもよい．

In [5]:
B[:]

8-element Vector{Float64}:
 0.6117275510785916
 0.4734555760000845
 0.6339529180095502
 0.830435097104653
 0.7766823530347728
 0.9694329613133161
 0.854543242553403
 0.8580472759841979

## 行列の行・列ごとの正規化
シミュレーションにおいてニューロン間の重み行列を行あるいは列ごとに正規化 (weight normalization)する場合がある．これは各ニューロンへの入力の大きさを同じにする働きや重みの発散を防ぐ役割がある．以下では行ごとの和を1にする．

In [6]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.588594  0.834252    0.673208
 0.515165  0.529187    0.337989
 0.829118  0.00561079  0.0630225

In [7]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.304517  0.609366    0.626695
 0.266528  0.386536    0.314637
 0.428955  0.00409831  0.0586682

In [8]:
println(sum(Wnormed, dims=1))

[1.0 1.0 1.0]


## 行列の結合 (concatenate)
行列の結合はMATLABに近い形式で行うことができる．まず，2つの行列A, Bを用意する．

In [9]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

### 水平結合 (Horizontal concatenation)
`hcat`を使うやり方と，`[ ]`を使うやり方がある．

In [11]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [12]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

なお，MATLABのように次のようにすると正しく結合はされない．

In [13]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

### 垂直結合 (Vertical concatenation)

In [14]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [15]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [16]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

## 配列に新しい軸を追加
要はnumpyでの`A[None, :]`や`A[np.newaxis, :]`のようなことがしたい場合．やや面倒だが，`reshape`を使うか，`[CartesianIndex()]`を用いる．

In [17]:
v = rand(3)

3-element Vector{Float64}:
 0.4619052621569364
 0.35539244823238003
 0.2569157728848581

In [18]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.461905  0.355392  0.256916

## Array{Array{Float64, x},1}をArray{Float64, x+1}に変換
numpyでは`array([matrix for i in range()])`などを用いると，1次元配列のリストを2次元配列に変換できた．Juliaでも同様にする場合は`hcat(...)`や`cat(...)`を用いる．

In [19]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : 

Vector

{Vector{Float64}}
Size : (5,)


In [20]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : LinearAlgebra.Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


以下は多次元配列の場合．`cat(...)`で配列を結合し，`permitedims`で転置する．

In [21]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [22]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)


## 二項分布 (bernoulli distribution)のサンプリング

In [23]:
p = 0.7
N = 100

100

In [24]:
using BenchmarkTools

In [25]:
@benchmark floor.(p .+ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.91 KiB
  allocs estimate:  7
  --------------
  minimum time:     849.254 ns (0.00% GC)
  median time:      880.597 ns (0.00% GC)
  mean time:        951.132 ns (2.69% GC)
  maximum time:     10.875 μs (90.12% GC)
  --------------
  samples:          10000
  evals/sample:     67

In [26]:
println(sum(floor.(p .+ rand(N)) .== 1.0) / N) 

0.7


In [27]:
@benchmark 1.0f0 * (p .≥ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.55 KiB
  allocs estimate:  6
  --------------
  minimum time:     961.905 ns (0.00% GC)
  median time:      1.000 μs (0.00% GC)
  mean time:        1.103 μs (2.45% GC)
  maximum time:     41.590 μs (96.76% GC)
  --------------
  samples:          10000
  evals/sample:     21

In [28]:
println(sum(1.0f0 * (p .≥ rand(N)) .== 1.0) / N) 

0.68


## Roth's column lemma

Roth's column lemmaは，例えば，$A, B, C$が与えられていて，$X$を未知とするときの方程式 $AXB = C$を考えると，この方程式は

$$
(B^\top \otimes A)\text{vec}(X) = \text{vec}(AXB)=\text{vec}(C)
$$

の形に書き下すことができる，というものである．$\text{vec}(\cdot)$はvec作用素（行列を列ベクトル化する作用素）である．`vec(X) = vcat(X...)`で実現できる．Roth's column lemmaを用いれば，$AXB = C$の解は

$$
X = \text{vec}^{-1}\left((B^\top \otimes A)^{-1}\text{vec}(C)\right)
$$

として得られる．ただし，$\text{vec}(\cdot)^{-1}$は列ベクトルを行列に戻す作用素(inverse of the vectorization operator)である．`reshape()`で実現できる．2つの作用素をまとめると，

$$
\begin{align}
\text{vec} &: R^{m\times n}\to R^{mn}\\
\text{vec}^{−1} &: R^{mn}\to R^{m×n}
\end{align}
$$

であり，$\text{vec}^{−1}\left(\text{vec}(X)\right)=X\ (\text{for all}\ X\in R^{m\times n})，\text{vec}\left(\text{vec}^{−1}(x)\right)=x\ (\text{for all}\ x \in R^{mn})$となる．

In [29]:
using LinearAlgebra, Kronecker, Random

In [30]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [31]:
vec(X) = vcat(X...)

vec (generic function with 1 method)

In [32]:
X = reshape((B' ⊗ A) \ vec(C), (m, m))

4×4 Matrix{Float64}:
   2.5579      52.5465     63.0954     76.0301
  -0.530953     4.60702     7.83321     8.76188
   4.05557     73.8125     87.2212    105.516
 -11.5792    -216.524    -256.825    -310.406

In [33]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

## "splat" operator ... 
https://docs.julialang.org/en/v1/base/base/#...

## broadcastingの回避

In [34]:
foo(a,b) = sum(a) + b

foo (generic function with 1 method)

In [35]:
println(foo.(Ref([1,2]),[3,4,5]))
println(foo.(([1,2],), [3,4,5]))
println(foo.([[1,2]], [3,4,5]))

[6, 7, 8]
[6, 7, 8]


[6, 7, 8]


## `var`の使用

In [36]:
var"log(θ+μ)" = 10

10

## reshapeにおける残りの次元の指定
numpyにおいては(2, 3, 5)次元の配列に対し，reshape(-1, 5)を行うと(6, 5)次元の配列となった．これと同様なことは，Juliaでは:を使うことで実装できる．

In [37]:
a = rand(2,3,5)
b = reshape(a, (:, 5))

6×5 Matrix{Float64}:
 0.0518554  0.180986     0.272303   0.762115  0.267639
 0.821883   0.000636878  0.534754   0.11266   0.487096
 0.708157   0.599136     0.860235   0.372236  0.49659
 0.748441   0.900505     0.0707445  0.278289  0.596447
 0.678209   0.644506     0.13227    0.163999  0.545261
 0.456953   0.0634696    0.233659   0.586786  0.739676