# 線形代数

本節ではJuliaでの線形代数における操作の取り扱いに関して説明する．Juliaにおける線形代数の記法は概ねMATLABと同様であり，処理を簡便に記載できる．

### 行列およびベクトルの作成
Juliaは列ベクトルが基本．$\mathbf{a}=[a_1, a_2, \ldots, a_n]^\top$

In [ ]:
v = [1.0, 2.0, 3.0]  # 列ベクトル

$$
\begin{equation}
\mathbf{A} =\left[\begin{array}{ccc}
a_{11} & \cdots & a_{1n} \\
\vdots & \ddots & \vdots  \\
a_{1n} & \cdots & a_{nn}
\end{array}\right]
\in \mathbb{R}^n
\end{equation}
$$

行列$\mathbf{A}$の$(i, j)$成分を$\mathbf{A}_{ij}=a_{ij}$とする．

In [ ]:
# 行列の定義
A = [1 2 3; 4 5 6; 7 8 9]  # 3x3 行列

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [13]:
zeros(3, 3)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [14]:
ones(3, 2)

3×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [17]:
fill(5, 2, 3)

2×3 Matrix{Int64}:
 5  5  5
 5  5  5

### 行列の基本演算
加減算

In [6]:
B = [9 8 7; 6 5 4; 3 2 1]

3×3 Matrix{Int64}:
 9  8  7
 6  5  4
 3  2  1

In [26]:
A + B  # 要素ごとに加算

3×3 Matrix{Int64}:
 10  10  10
 10  10  10
 10  10  10

In [27]:
A - B  # 要素ごとに減算

3×3 Matrix{Int64}:
 -8  -6  -4
 -2   0   2
  4   6   8

In [28]:
# スカラー倍
2 * A  # 各要素を2倍

3×3 Matrix{Int64}:
  2   4   6
  8  10  12
 14  16  18

乗じる2つの変数が行列同士の場合，`*`は行列積を実行する．`.*`を用いる場合は要素積（アダマール積）を実行する．これはMATLABと同様であり，Pythonとは異なる．

In [29]:
# 行列積
A * B  # 行列積（ドット積ではない）

3×3 Matrix{Int64}:
  30   24  18
  84   69  54
 138  114  90

In [30]:
A .* B 

3×3 Matrix{Int64}:
  9  16  21
 24  25  24
 21  16   9

### 転置と共役転置
転置行列や複素共役転置も簡単に計算

In [19]:
# 転置
At = transpose(A)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [32]:
# 共役転置（複素数を扱う場合）
Ac = A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [31]:
C = A + B .* im

3×3 Matrix{Complex{Int64}}:
 1+9im  2+8im  3+7im
 4+6im  5+5im  6+4im
 7+3im  8+2im  9+1im

In [33]:
Cc = C'

3×3 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1-9im  4-6im  7-3im
 2-8im  5-5im  8-2im
 3-7im  6-4im  9-1im

In [ ]:
using LinearAlgebra

Juliaは線形代数に非常に強力なサポートを提供しており、行列やベクトルの操作を効率的かつ直感的に行うことができます。以下に、よく使われる線形代数の操作を具体例を交えながら説明します。


も簡単に計算



### 4. **逆行列と行列式**
Juliaは逆行列や行列式も計算できます。ただし、逆行列は直接計算するよりも、線形方程式を解く方法が推奨さ

``julia
# 逆行列
inv_A = inv(A)  # A が正則行列である場合のみ

# 行列式
det_A = d

  # A の行列式
```

---

### 5. **固有値と固有ベクトル**
行列の固有値および固有ベクトルの計算。

```julia
eigvals_A = eigvals(A)        # 固有値
eigvecs_A = eigvecs(A)        # 固有ベクトル
eig_A = eigen(A)              # 固有値と固有ベクトルのペア
```

---

### 6. **線形方程式の解法**
線形方程式 \( Ax = b \) の解を効率的に求めます。

```julia
b = [1, 2, 3]
x = A \ b  # A*x = b の解を計算
```

---

### 7. **特異値分解（SVD）**
特異値分解により、行列を分解できます。

```julia
U, S, V = svd(A)
# U, S, V の意味:
# A = U * Diagonal(S) * V'
```

---

### 8. **クロネッカー積**
2つの行列のクロネッカー積を計算します。

```julia
kron_A_B = kron(A, B)
```

---

### 9. **行列の部分選択**
Juliaでは行列の一部を簡単に抽出できます。

```julia
# 特定の行や列を選択
row1 = A[1, :]   # A の第1行
col2 = A[:, 2]   # A の第2列

# サブマトリックス
sub_A = A[1:2, 2:3]  # 1-2行, 2-3列の部分行列
```

---

### 10. **行列のランクと条件数**
行列の性質を調べる際に役立ちます。

```julia
rank_A = rank(A)       # A のランク
cond_A = cond(A)       # A の条件数
```

---

### まとめ
Juliaでは、線形代数の演算が高度に最適化されており、`LinearAlgebra` モジュールを使うことでさらに多くの機能を利用できます。例えば、特定の分解手法や数値計算を行う際に役立ちます。

```julia
using LinearAlgebra
```

このモジュールをインポートすると、さらに多くの高度な関数や操作を使用できます！

In [1]:
using LinearAlgebra

## 要素ごとの演算
### 行列の行・列ごとの正規化
シミュレーションにおいてニューロン間の重み行列を行あるいは列ごとに正規化 (weight normalization)する場合がある．これは各ニューロンへの入力の大きさを同じにする働きや重みの発散を防ぐ役割がある．以下では行ごとの和を1にする．

In [4]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.346295  0.323508  0.962472
 0.406592  0.679734  0.552339
 0.927452  0.788856  0.981346

In [5]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.206086  0.180519  0.385582
 0.24197   0.379295  0.221276
 0.551943  0.440186  0.393143

In [6]:
println(sum(Wnormed, dims=1))

[1.0 1.0 1.0]


### 行列の結合 (concatenate)
行列の結合はMATLABに近い形式で行うことができる．まず，2つの行列A, Bを用意する．

In [7]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [8]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

### 水平結合 (Horizontal concatenation)
`hcat`を使うやり方と，`[ ]`を使うやり方がある．

In [10]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [10]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

なお，MATLABのように次のようにすると正しく結合はされない．

In [11]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

### 垂直結合 (Vertical concatenation)

aaa

In [12]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [13]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [14]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

## 配列に新しい軸を追加
要はnumpyでの`A[None, :]`や`A[np.newaxis, :]`のようなことがしたい場合．やや面倒だが，`reshape`を使うか，`[CartesianIndex()]`を用いる．

In [15]:
v = rand(3)

3-element Vector{Float64}:
 0.9225597515419179
 0.658120481093438
 0.41401801671066496

In [16]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.92256  0.65812  0.414018

### 単位行列

aaa

In [17]:
I

UniformScaling{Bool}
true*I

In [18]:
I(3)

3×3 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

### 対角行列

aaa

### 線形行列方程式

$\mathbf{A}\mathbf{x}=\mathbf{b}$は$\mathbf{A}$が正則の場合，逆行列が存在し，$\mathbf{x}=\mathbf{A}^{-1}\mathbf{b}$が解となる．

In [33]:
A = rand(2,2)
b = rand(2)

2-element Vector{Float64}:
 0.5002132597166149
 0.03509562556923285

In [34]:
x = inv(A) * b

2-element Vector{Float64}:
 -0.1805788303672428
  0.8082531148175677

Juliaではバックスラッシュ演算子 `\`を用いることで明示的に逆行列を計算せずに解を求めることができる．

In [35]:
x = A \ b

2-element Vector{Float64}:
 -0.1805788303672428
  0.8082531148175676

## Roth's column lemma

Roth's column lemmaは，例えば，$A, B, C$が与えられていて，$X$を未知とするときの方程式 $AXB = C$を考えると，この方程式は

$$
\begin{equation}
(B^\top \otimes A)\text{vec}(X) = \text{vec}(AXB)=\text{vec}(C)
\end{equation}
$$

の形に書き下すことができる，というものである．$\text{vec}(\cdot)$はvec作用素（行列を列ベクトル化する作用素）である．`vec(X) = vcat(X...)`で実現できる．Roth's column lemmaを用いれば，$AXB = C$の解は

$$
\begin{equation}
X = \text{vec}^{-1}\left((B^\top \otimes A)^{-1}\text{vec}(C)\right)
\end{equation}
$$

として得られる．ただし，$\text{vec}(\cdot)^{-1}$は列ベクトルを行列に戻す作用素(inverse of the vectorization operator)である．`reshape()`で実現できる．2つの作用素をまとめると，

$$
\begin{align}
\text{vec} &: R^{m\times n}\to R^{mn}\\
\text{vec}^{−1} &: R^{mn}\to R^{m\times n}
\end{align}
$$

であり，$\text{vec}^{−1}\left(\text{vec}(X)\right)=X\ (\text{for all}\ X\in R^{m\times n})，\text{vec}\left(\text{vec}^{−1}(x)\right)=x\ (\text{for all}\ x \in R^{mn})$となる．

In [21]:
using LinearAlgebra, Kronecker, Random

In [22]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [23]:
X = reshape((B' ⊗ A) \ vec(C), (m, m))

4×4 Matrix{Float64}:
  25.5193   -29.5701     5.09719  -18.3365
 -61.7388    71.768    -12.3934    44.6203
   5.53255   -6.36443    1.09258   -3.92298
   6.70725   -7.05331    1.14599   -4.0074

In [24]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

### 配列の1次元化
配列を一次元化(flatten)する方法．まずは3次元配列を作成する．

In [25]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.915692  0.18149
 0.132838  0.0376235

[:, :, 2] =
 0.807789  0.297739
 0.569867  0.705417

用意されている`flatten`を素直に用いると次のようになる．

In [26]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.9156924090979948
 0.13283838898511735
 0.18149003405285813
 0.03762345094967079
 0.8077889408656388
 0.5698673388911334
 0.297739498855886
 0.7054169935372759

ただし，単に`B[:]`とするだけでもよい．

In [27]:
B[:]

8-element Vector{Float64}:
 0.9156924090979948
 0.13283838898511735
 0.18149003405285813
 0.03762345094967079
 0.8077889408656388
 0.5698673388911334
 0.297739498855886
 0.7054169935372759

### reshapeにおける残りの次元の指定
numpyにおいては(2, 3, 5)次元の配列に対し，reshape(-1, 5)を行うと(6, 5)次元の配列となった．これと同様なことは，Juliaでは:を使うことで実装できる．

In [28]:
a = rand(2,3,5)
b = reshape(a, (:, 5))

6×5 Matrix{Float64}:
 0.286014   0.923302  0.174386   0.10705    0.744143
 0.457232   0.234084  0.149783   0.684196   0.21295
 0.308209   0.712286  0.903116   0.487475   6.84179e-6
 0.0566201  0.526367  0.235321   0.0381212  0.336639
 0.0933628  0.980388  0.0258844  0.0371784  0.849971
 0.384149   0.628456  0.077691   0.970843   0.678124

## Array{Array{Float64, x},1}をArray{Float64, x+1}に変換
numpyでは`array([matrix for i in range()])`などを用いると，1次元配列のリストを2次元配列に変換できた．Juliaでも同様にする場合は`hcat(...)`や`cat(...)`を用いる．`...`はsplat operatorと呼ばれる．

In [11]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : Vector{Vector{Float64}}
Size : (5,)


In [12]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


In [13]:
stack(A1)

3×5 Matrix{Float64}:
 0.399752  1.0085    0.36412    0.66242   1.06852
 0.250858  0.946007  1.07921    0.627488  0.179271
 0.75941   0.899138  0.0960996  3.52572   0.717514

以下は多次元配列の場合．`cat(...)`で配列を結合し，`permitedims`で転置する．

In [14]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [15]:
stack(B1)

3×4×5×6 Array{Float64, 4}:
[:, :, 1, 1] =
 0.88996    0.418819  0.317106  0.809881
 0.0656426  0.403243  0.748969  0.656944
 0.0165343  0.21815   0.20768   0.271664

[:, :, 2, 1] =
 0.924109  0.874625  0.548064   0.0665163
 0.438622  0.808703  0.881086   0.777017
 0.740098  0.48068   0.0283703  0.667576

[:, :, 3, 1] =
 0.316527   0.26011   0.453848  0.33607
 0.610262   0.285777  0.888585  0.645278
 0.0159621  0.470272  0.430346  0.686911

[:, :, 4, 1] =
 0.306327  0.521515   0.125245  0.28525
 0.436886  0.397245   0.876463  0.822274
 0.391734  0.0093844  0.210796  0.080409

[:, :, 5, 1] =
 0.720239  0.597256   0.00176386  0.287453
 0.59386   0.0274512  0.321321    0.0833419
 0.655899  0.303632   0.787094    0.543664

[:, :, 1, 2] =
 1.52439   0.524795  0.0910437  1.94272
 0.955208  0.638171  1.8238     0.30505
 0.634682  1.17551   0.770143   1.01951

[:, :, 2, 2] =
 1.55138   1.10778   0.825705  1.71204
 0.778812  0.167395  1.05283   0.496133
 1.49202   1.04271   0.768803  0.888104

[

In [32]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)
