In [1]:
function wrong!(a::Array)
    a = ones(size(a))
end

function right!(a::Array)
    a[:] = ones(size(a))
end

right! (generic function with 1 method)

In [2]:
using Random
v = rand(2, 2)
println("v : ", v)

wrong!(v)
println("wrong : ", v)

right!(v)
println("right : ", v)

v : 

[0.005576574001808554 0.8557056006265202; 0.9264780791310023 0.7987745277209479]
wrong : [0.005576574001808554 0.8557056006265202; 0.9264780791310023 0.7987745277209479]
right : [1.0 1.0; 1.0 1.0]


In [3]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.775124  0.849931
 0.725282  0.71391

[:, :, 2] =
 0.493965  0.812393
 0.774293  0.526379

In [4]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.7751237088001743
 0.7252819087711331
 0.849931003989089
 0.7139096721994873
 0.49396508548652096
 0.7742929909810052
 0.8123932209148093
 0.526379424652242

In [5]:
B[:]

8-element Vector{Float64}:
 0.7751237088001743
 0.7252819087711331
 0.849931003989089
 0.7139096721994873
 0.49396508548652096
 0.7742929909810052
 0.8123932209148093
 0.526379424652242

In [6]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.991477  0.621815   0.87384
 0.469206  0.0498323  0.542353
 0.382387  0.884882   0.818279

In [7]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.537949  0.399488  0.391072
 0.254579  0.032015  0.242721
 0.207473  0.568497  0.366207

In [8]:
println(sum(Wnormed, dims=1))

[1.0 1.0 1.0]


In [9]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

In [11]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [12]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [13]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

In [14]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [15]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [16]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

In [17]:
v = rand(3)

3-element Vector{Float64}:
 0.7248384376463681
 0.9353658446779063
 0.380279503045418

In [18]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.724838  0.935366  0.38028

In [19]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : 

Vector

{Vector{Float64}}
Size : (5,)


In [20]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : LinearAlgebra.Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


In [21]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [22]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)


In [23]:
p = 0.7
N = 100

100

In [24]:
using BenchmarkTools

In [25]:
@benchmark floor.(p .+ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.91 KiB
  allocs estimate:  7
  --------------
  minimum time:     856.000 ns (0.00% GC)
  median time:      888.000 ns (0.00% GC)
  mean time:        960.202 ns (2.42% GC)
  maximum time:     9.373 μs (89.46% GC)
  --------------
  samples:          10000
  evals/sample:     75

In [26]:
println(sum(floor.(p .+ rand(N)) .== 1.0) / N) 

0.76


In [27]:
@benchmark 1.0f0 * (p .≥ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.55 KiB
  allocs estimate:  6
  --------------
  minimum time:     923.684 ns (0.00% GC)
  median time:      968.421 ns (0.00% GC)
  mean time:        1.040 μs (2.44% GC)
  maximum time:     23.334 μs (95.39% GC)
  --------------
  samples:          10000
  evals/sample:     38

In [28]:
println(sum(1.0f0 * (p .≥ rand(N)) .== 1.0) / N) 

0.67


In [29]:
using LinearAlgebra, Kronecker, Random

In [30]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [31]:
vec(X) = vcat(X...)

vec (generic function with 1 method)

In [32]:
X = reshape((B' ⊗ A)^-1 * vec(C), (m, m))

4×4 Matrix{Float64}:
  -48.1315   -1.8168    -17.4929    25.8434
  274.362    38.0334    164.524   -149.846
  -35.6901   -4.34955   -20.0016    19.4379
 -435.658   -51.513    -240.453    237.128

In [33]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0