In [1]:
function wrong!(a::Array)
    a = ones(size(a))
end

function right!(a::Array)
    a[:] = ones(size(a))
end

right! (generic function with 1 method)

In [2]:
using Random
v = rand(2, 2)
println("v : ", v)

wrong!(v)
println("wrong : ", v)

right!(v)
println("right : ", v)

v : 

[0.005267290785053502 0.43379396626954914; 0.1696259987499149 0.6084087875201685]
wrong : [0.005267290785053502 0.43379396626954914; 0.1696259987499149 0.6084087875201685]
right : [1.0 1.0; 1.0 1.0]


In [3]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.243269  0.932779
 0.520383  0.0242472

[:, :, 2] =
 0.119226  0.531315
 0.79391   0.893931

In [4]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.2432690778540889
 0.5203832392202838
 0.9327785412153073
 0.024247193093797303
 0.11922647240783002
 0.7939096911754226
 0.5313148268279924
 0.8939305428143489

In [5]:
B[:]

8-element Vector{Float64}:
 0.2432690778540889
 0.5203832392202838
 0.9327785412153073
 0.024247193093797303
 0.11922647240783002
 0.7939096911754226
 0.5313148268279924
 0.8939305428143489

In [6]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.128056  0.432833  0.613254
 0.294777  0.962931  0.553476
 0.67827   0.87947   0.854013

In [7]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.116298  0.190237  0.303479
 0.267711  0.423223  0.273897
 0.615991  0.386541  0.422623

In [8]:
println(sum(Wnormed, dims=1))

[1.0 0.9999999999999998 1.0]


In [9]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

In [11]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [12]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [13]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

In [14]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [15]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [16]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

In [17]:
v = rand(3)

3-element Vector{Float64}:
 0.7595133636159019
 0.68392254312918
 0.28155316035514866

In [18]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.759513  0.683923  0.281553

In [19]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : Vector

{Vector{Float64}}
Size : (5,)


In [20]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : LinearAlgebra.Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


In [21]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [22]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)


In [23]:
p = 0.7
N = 100

100

In [24]:
using BenchmarkTools

In [25]:
@benchmark floor.(p .+ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.91 KiB
  allocs estimate:  7
  --------------
  minimum time:     862.667 ns (0.00% GC)
  median time:      893.333 ns (0.00% GC)
  mean time:        941.192 ns (2.78% GC)
  maximum time:     13.239 μs (92.12% GC)
  --------------
  samples:          10000
  evals/sample:     75

In [26]:
println(sum(floor.(p .+ rand(N)) .== 1.0) / N) 

0.59


In [27]:
@benchmark 1.0f0 * (p .≥ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.55 KiB
  allocs estimate:  6
  --------------
  minimum time:     914.815 ns (0.00% GC)
  median time:      966.667 ns (0.00% GC)
  mean time:        1.043 μs (2.91% GC)
  maximum time:     38.878 μs (96.46% GC)
  --------------
  samples:          10000
  evals/sample:     27

In [28]:
println(sum(1.0f0 * (p .≥ rand(N)) .== 1.0) / N) 

0.66


In [29]:
using LinearAlgebra, Kronecker, Random

In [30]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [31]:
vec(X) = vcat(X...)

vec (generic function with 1 method)

In [32]:
X = reshape((B' ⊗ A)^-1 * vec(C), (m, m))

4×4 Matrix{Float64}:
 -0.0437291  -3.80727     6.2288   -2.79825
 -0.96497    -5.3306      9.40564  -4.49945
  2.69899    14.1014    -24.9922   11.9968
  0.280477   -0.944033    1.32377  -0.50637

In [33]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0