In [1]:
function wrong!(a::Array)
    a = ones(size(a))
end

function right!(a::Array)
    a[:] = ones(size(a))
end

right! (generic function with 1 method)

In [2]:
using Random
v = rand(2, 2)
println("v : ", v)

wrong!(v)
println("wrong : ", v)

right!(v)
println("right : ", v)

v : 

[0.34045657122557615 0.27554462236550903; 0.4703396774195381 0.681556925480835]
wrong : [0.34045657122557615 0.27554462236550903; 0.4703396774195381 0.681556925480835]
right : [1.0 1.0; 1.0 1.0]


In [3]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.00529206  0.362073
 0.961648    0.0596108

[:, :, 2] =
 0.773794  0.0721447
 0.443574  0.88182

In [4]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.005292059282109296
 0.961647523160213
 0.3620729421295156
 0.05961081514080513
 0.7737936777782087
 0.44357433199284624
 0.0721446924452327
 0.8818199245526218

In [5]:
B[:]

8-element Vector{Float64}:
 0.005292059282109296
 0.961647523160213
 0.3620729421295156
 0.05961081514080513
 0.7737936777782087
 0.44357433199284624
 0.0721446924452327
 0.8818199245526218

In [6]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.771075  0.873442  0.712519
 0.491367  0.301352  0.497528
 0.214799  0.823613  0.389931

In [7]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.52197   0.437069  0.44533
 0.332625  0.150796  0.310959
 0.145406  0.412135  0.24371

In [8]:
println(sum(Wnormed, dims=1))

[1.0 1.0 1.0]


In [9]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

In [11]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [12]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [13]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

In [14]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [15]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [16]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

In [17]:
v = rand(3)

3-element Vector{Float64}:
 0.5415479850585573
 0.06332176366571052
 0.6662145542466062

In [18]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.541548  0.0633218  0.666215

In [19]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : Vector{Vector{Float64}}


Size : (5,)


In [20]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : LinearAlgebra.Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


In [21]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [22]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)


In [23]:
p = 0.7
N = 100

100

In [24]:
using BenchmarkTools

In [25]:
@benchmark floor.(p .+ rand(N))

BenchmarkTools.Trial: 10000 samples with 55 evaluations.
 Range (min … max):  861.818 ns …  30.847 μs  ┊ GC (min … max): 0.00% … 95.11%
 Time  (median):     896.364 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):     1.032 μs ± 908.149 ns  ┊ GC (mean ± σ):  3.73% ±  4.46%

  █▇▅▄▃▂▁              ▂▁▁                                      ▁
  ███████▇▇▆▆▆▆▅▅▇▅▆▅▅████▇▇▇▆▆▆▅▅▅▄▅▅▄▄▄▄▃▄▄▃▄▄▄▃▃▃▅▃▃▃▃▂▃▄▂▃▃ █
  862 ns        Histogram: log(frequency) by time       2.85 μs <

 Memory estimate: 1.91 KiB, allocs estimate: 7.

In [26]:
println(sum(floor.(p .+ rand(N)) .== 1.0) / N) 

0.75


In [27]:
@benchmark 1.0f0 * (p .≥ rand(N))

BenchmarkTools.Trial: 10000 samples with 21 evaluations.
 Range (min … max):  942.857 ns … 75.395 μs  ┊ GC (min … max): 0.00% … 97.52%
 Time  (median):       1.000 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):     1.156 μs ±  1.861 μs  ┊ GC (mean ± σ):  4.14% ±  2.58%

  ▄██▇▆▃▁                  ▁▁▂▂▂▂▂▂▁▁▁▁                        ▂
  ████████████▇▇▆▄▅▆▅▄▄▆▆███████████████▇▇▇▇▇▆▆▅▄▅▅▄▄▄▄▃▄▅▄▄▃▂ █
  943 ns        Histogram: log(frequency) by time      2.15 μs <

 Memory estimate: 1.53 KiB, allocs estimate: 6.

In [28]:
println(sum(1.0f0 * (p .≥ rand(N)) .== 1.0) / N) 

0.69


In [29]:
using LinearAlgebra, Kronecker, Random

In [30]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [31]:
vec(X) = vcat(X...)

vec (generic function with 1 method)

In [32]:
X = reshape((B' ⊗ A) \ vec(C), (m, m))

4×4 Matrix{Float64}:
 -888.913   1330.12    922.106   1738.86
  -91.7101   132.596    89.7183   177.929
  -52.3583    80.113    56.3792   102.983
  -71.3051    87.5883   51.63     133.417

In [33]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [34]:
foo(a,b) = sum(a) + b

foo (generic function with 1 method)

In [35]:
println(foo.(Ref([1,2]),[3,4,5]))
println(foo.(([1,2],), [3,4,5]))
println(foo.([[1,2]], [3,4,5]))

[6, 7, 8]
[6, 7, 8]


[6, 7, 8]


In [36]:
var"log(θ+μ)" = 10

10

In [37]:
a = rand(2,3,5)
b = reshape(a, (:, 5))

6×5 Matrix{Float64}:
 0.908084  0.722132   0.396659    0.81059    0.601935
 0.662575  0.466184   0.00450544  0.703617   0.301845
 0.772097  0.0846089  0.81668     0.0524018  0.167286
 0.439347  0.0316409  0.558907    0.38736    0.117209
 0.510455  0.193172   0.208884    0.949195   0.67698
 0.383945  0.26303    0.209588    0.282378   0.150833