In [1]:
function wrong!(a::Array)
    a = ones(size(a))
end

function right!(a::Array)
    a[:] = ones(size(a))
end

right! (generic function with 1 method)

In [2]:
using Random
v = rand(2, 2)
println("v : ", v)

wrong!(v)
println("wrong : ", v)

right!(v)
println("right : ", v)

v : [0.5832535214226895 0.9863239196768177; 0.9385627748273042 0.6036749327061697]
wrong : [0.5832535214226895 0.9863239196768177; 0.9385627748273042 0.6036749327061697]
right : [1.0 1.0; 1.0 1.0]


In [3]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.171359  0.970301
 0.368827  0.400136

[:, :, 2] =
 0.415898  0.193467
 0.39925   0.588116

In [4]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.17135901366980444
 0.3688271762434565
 0.9703008447114903
 0.4001358330916738
 0.41589764263469364
 0.39925026276573816
 0.19346717296946458
 0.5881157611777139

In [5]:
B[:]

8-element Vector{Float64}:
 0.17135901366980444
 0.3688271762434565
 0.9703008447114903
 0.4001358330916738
 0.41589764263469364
 0.39925026276573816
 0.19346717296946458
 0.5881157611777139

In [6]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.89766   0.251363  0.621109
 0.584915  0.156382  0.985538
 0.288508  0.387411  0.0143406

In [7]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.506842  0.316118  0.383167
 0.330259  0.196668  0.607986
 0.162899  0.487214  0.00884685

In [8]:
println(sum(Wnormed, dims=1))

[0.9999999999999999 1.0 1.0]


In [9]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

In [11]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [12]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [13]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

In [14]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [15]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [16]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

In [17]:
v = rand(3)

3-element Vector{Float64}:
 0.29868483872953977
 0.9074295824314997
 0.7142987103485341

In [18]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.298685  0.90743  0.714299

In [19]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : Vector

{Vector{Float64}}
Size : (5,)


In [20]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : LinearAlgebra.Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


In [21]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [22]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)


In [23]:
p = 0.7
N = 100

100

In [24]:
using BenchmarkTools

In [25]:
@benchmark floor.(p .+ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.91 KiB
  allocs estimate:  7
  --------------
  minimum time:     866.038 ns (0.00% GC)
  median time:      896.226 ns (0.00% GC)
  mean time:        967.730 ns (2.68% GC)
  maximum time:     14.879 μs (87.81% GC)
  --------------
  samples:          10000
  evals/sample:     53

In [26]:
println(sum(floor.(p .+ rand(N)) .== 1.0) / N) 

0.68


In [27]:
@benchmark 1.0f0 * (p .≥ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.55 KiB
  allocs estimate:  6
  --------------
  minimum time:     935.714 ns (0.00% GC)
  median time:      985.714 ns (0.00% GC)
  mean time:        1.068 μs (2.48% GC)
  maximum time:     33.625 μs (96.30% GC)
  --------------
  samples:          10000
  evals/sample:     28

In [28]:
println(sum(1.0f0 * (p .≥ rand(N)) .== 1.0) / N) 

0.73


In [29]:
using LinearAlgebra, Kronecker, Random

In [30]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [31]:
vec(X) = vcat(X...)

vec (generic function with 1 method)

In [32]:
X = reshape((B' ⊗ A) \ vec(C), (m, m))

4×4 Matrix{Float64}:
  -6.36945   -12.1054    -11.5015   -37.2391
  -7.43169   -13.7294    -12.4696   -37.2072
 -10.8617    -20.535     -19.3533   -61.7945
   0.569664    0.213792   -1.06218  -10.4073

In [33]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [34]:
foo(a,b) = sum(a) + b

foo (generic function with 1 method)

In [35]:
println(foo.(Ref([1,2]),[3,4,5]))
println(foo.(([1,2],), [3,4,5]))
println(foo.([[1,2]], [3,4,5]))

[6, 7, 8]
[6, 7, 8]


[6, 7, 8]


In [36]:
var"log(θ+μ)" = 10

10

In [37]:
a = rand(2,3,5)
b = reshape(a, (:, 5))

6×5 Matrix{Float64}:
 0.833379   0.506352  0.587947   0.784246  0.0260247
 0.506091   0.826972  0.279171   0.86387   0.0400987
 0.0645915  0.594297  0.126421   0.181552  0.688678
 0.287908   0.554669  0.265179   0.229792  0.311631
 0.948209   0.736961  0.0463345  0.39206   0.84656
 0.254488   0.999719  0.771749   0.868979  0.192396