In [1]:
function wrong!(a::Array)
    a = ones(size(a))
end

function right!(a::Array)
    a[:] = ones(size(a))
end

right! (generic function with 1 method)

In [2]:
using Random
v = rand(2, 2)
println("v : ", v)

wrong!(v)
println("wrong : ", v)

right!(v)
println("right : ", v)

v : 

[0.5186591134015561 0.6048708090823378; 0.238331348187236 0.20953434348009425]
wrong : [0.5186591134015561 0.6048708090823378; 0.238331348187236 0.20953434348009425]
right : [1.0 1.0; 

1.0 1.0]


In [3]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.611728  0.633953
 0.473456  0.830435

[:, :, 2] =
 0.776682  0.854543
 0.969433  0.858047

In [4]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.6117275510785916
 0.4734555760000845
 0.6339529180095502
 0.830435097104653
 0.7766823530347728
 0.9694329613133161
 0.854543242553403
 0.8580472759841979

In [5]:
B[:]

8-element Vector{Float64}:
 0.6117275510785916
 0.4734555760000845
 0.6339529180095502
 0.830435097104653
 0.7766823530347728
 0.9694329613133161
 0.854543242553403
 0.8580472759841979

In [6]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.588594  0.834252    0.673208
 0.515165  0.529187    0.337989
 0.829118  0.00561079  0.0630225

In [7]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.304517  0.609366    0.626695
 0.266528  0.386536    0.314637
 0.428955  0.00409831  0.0586682

In [8]:
println(sum(Wnormed, dims=1))

[1.0 1.0 1.0]


In [9]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

In [11]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [12]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [13]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

In [14]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [15]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [16]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

In [17]:
v = rand(3)

3-element Vector{Float64}:
 0.4619052621569364
 0.35539244823238003
 0.2569157728848581

In [18]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.461905  0.355392  0.256916

In [19]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : 

Vector

{Vector{Float64}}
Size : (5,)


In [20]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : LinearAlgebra.Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


In [21]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [22]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)


In [23]:
p = 0.7
N = 100

100

In [24]:
using BenchmarkTools

In [25]:
@benchmark floor.(p .+ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.91 KiB
  allocs estimate:  7
  --------------
  minimum time:     849.254 ns (0.00% GC)
  median time:      880.597 ns (0.00% GC)
  mean time:        951.132 ns (2.69% GC)
  maximum time:     10.875 μs (90.12% GC)
  --------------
  samples:          10000
  evals/sample:     67

In [26]:
println(sum(floor.(p .+ rand(N)) .== 1.0) / N) 

0.7


In [27]:
@benchmark 1.0f0 * (p .≥ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.55 KiB
  allocs estimate:  6
  --------------
  minimum time:     961.905 ns (0.00% GC)
  median time:      1.000 μs (0.00% GC)
  mean time:        1.103 μs (2.45% GC)
  maximum time:     41.590 μs (96.76% GC)
  --------------
  samples:          10000
  evals/sample:     21

In [28]:
println(sum(1.0f0 * (p .≥ rand(N)) .== 1.0) / N) 

0.68


In [29]:
using LinearAlgebra, Kronecker, Random

In [30]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [31]:
vec(X) = vcat(X...)

vec (generic function with 1 method)

In [32]:
X = reshape((B' ⊗ A) \ vec(C), (m, m))

4×4 Matrix{Float64}:
   2.5579      52.5465     63.0954     76.0301
  -0.530953     4.60702     7.83321     8.76188
   4.05557     73.8125     87.2212    105.516
 -11.5792    -216.524    -256.825    -310.406

In [33]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [34]:
foo(a,b) = sum(a) + b

foo (generic function with 1 method)

In [35]:
println(foo.(Ref([1,2]),[3,4,5]))
println(foo.(([1,2],), [3,4,5]))
println(foo.([[1,2]], [3,4,5]))

[6, 7, 8]
[6, 7, 8]


[6, 7, 8]


In [36]:
var"log(θ+μ)" = 10

10

In [37]:
a = rand(2,3,5)
b = reshape(a, (:, 5))

6×5 Matrix{Float64}:
 0.0518554  0.180986     0.272303   0.762115  0.267639
 0.821883   0.000636878  0.534754   0.11266   0.487096
 0.708157   0.599136     0.860235   0.372236  0.49659
 0.748441   0.900505     0.0707445  0.278289  0.596447
 0.678209   0.644506     0.13227    0.163999  0.545261
 0.456953   0.0634696    0.233659   0.586786  0.739676