In [1]:
function wrong!(a::Array)
    a = ones(size(a))
end

function right!(a::Array)
    a[:] = ones(size(a))
end

right! (generic function with 1 method)

In [2]:
using Random
v = rand(2, 2)
println("v : ", v)

wrong!(v)
println("wrong : ", v)

right!(v)
println("right : ", v)

v : 

[0.9260629725247853 0.03603047943915172; 0.4257272042455853 0.3276915437718575]
wrong : [0.9260629725247853 0.03603047943915172; 0.4257272042455853 0.3276915437718575]
right : [1.0 1.0; 1.0 1.0]


In [3]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.979104  0.957247
 0.130638  0.747744

[:, :, 2] =
 0.601915  0.230052
 0.264066  0.210893

In [4]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.9791037472597044
 0.130638212083938
 0.9572469034641975
 0.7477443173968323
 0.6019150914630806
 0.2640658794403452
 0.230052259097423
 0.21089287814851665

In [5]:
B[:]

8-element Vector{Float64}:
 0.9791037472597044
 0.130638212083938
 0.9572469034641975
 0.7477443173968323
 0.6019150914630806
 0.2640658794403452
 0.230052259097423
 0.21089287814851665

In [6]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.603262  0.688243   0.729117
 0.764048  0.975049   0.585761
 0.258784  0.0572537  0.0725289

In [7]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.370989  0.400014   0.525525
 0.469867  0.566709   0.422198
 0.159144  0.0332765  0.0522766

In [8]:
println(sum(Wnormed, dims=1))

[1.0 1.0 1.0]


In [9]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

In [11]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [12]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [13]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

In [14]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [15]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [16]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

In [17]:
v = rand(3)

3-element Vector{Float64}:
 0.26191750042117445
 0.7680331216652516
 0.40519272523745187

In [18]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.261918  0.768033  0.405193

In [19]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : Vector

{Vector{Float64}}
Size : (5,)


In [20]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : LinearAlgebra.Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


In [21]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [22]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)


In [23]:
p = 0.7
N = 100

100

In [24]:
using BenchmarkTools

In [25]:
@benchmark floor.(p .+ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.91 KiB
  allocs estimate:  7
  --------------
  minimum time:     852.941 ns (0.00% GC)
  median time:      881.176 ns (0.00% GC)
  mean time:        944.774 ns (2.63% GC)
  maximum time:     8.999 μs (87.37% GC)
  --------------
  samples:          10000
  evals/sample:     85

In [26]:
println(sum(floor.(p .+ rand(N)) .== 1.0) / N) 

0.71


In [27]:
@benchmark 1.0f0 * (p .≥ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.55 KiB
  allocs estimate:  6
  --------------
  minimum time:     944.186 ns (0.00% GC)
  median time:      983.721 ns (0.00% GC)
  mean time:        1.047 μs (2.42% GC)
  maximum time:     20.321 μs (92.94% GC)
  --------------
  samples:          10000
  evals/sample:     43

In [28]:
println(sum(1.0f0 * (p .≥ rand(N)) .== 1.0) / N) 

0.72


In [29]:
using LinearAlgebra, Kronecker, Random

In [30]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [31]:
vec(X) = vcat(X...)

vec (generic function with 1 method)

In [32]:
X = reshape((B' ⊗ A)^-1 * vec(C), (m, m))

4×4 Matrix{Float64}:
  13.6197    27.2844   2.045    -17.8671
 -10.5188   -22.7872  -3.08732   14.8822
  28.8625    59.1315   5.48664  -38.6917
   4.69645   10.4046   1.58114   -6.7902

In [33]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [34]:
foo(a,b) = sum(a) + b

foo (generic function with 1 method)

In [35]:
println(foo.(Ref([1,2]),[3,4,5]))
println(foo.(([1,2],), [3,4,5]))
println(foo.([[1,2]], [3,4,5]))

[6, 7, 8]
[6, 7, 8]


[6, 7, 8]


In [36]:
var"log(θ+μ)" = 10

10