In [1]:
function wrong!(a::Array)
    a = ones(size(a))
end

function right!(a::Array)
    a[:] = ones(size(a))
end

right! (generic function with 1 method)

In [2]:
using Random
v = rand(2, 2)
println("v : ", v)

wrong!(v)
println("wrong : ", v)

right!(v)
println("right : ", v)

v : 

[0.8570112530790073 0.02668493226734414; 0.9313480702897132 0.6429393770493825]
wrong : [0.8570112530790073 0.02668493226734414; 0.9313480702897132 0.6429393770493825]
right : [1.0 1.0; 1.0 1.0]


In [3]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.792723  0.943819
 0.841571  0.89125

[:, :, 2] =
 0.759811  0.117631
 0.213332  0.592785

In [4]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.7927231846852263
 0.8415712405750733
 0.9438191507875473
 0.8912504551993605
 0.7598108442633569
 0.2133322545050702
 0.1176313938149589
 0.5927851654353755

In [5]:
B[:]

8-element Vector{Float64}:
 0.7927231846852263
 0.8415712405750733
 0.9438191507875473
 0.8912504551993605
 0.7598108442633569
 0.2133322545050702
 0.1176313938149589
 0.5927851654353755

In [6]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.58935   0.537614  0.495848
 0.284481  0.555958  0.913234
 0.418111  0.550877  0.911656

In [7]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.456174  0.326927  0.213659
 0.220197  0.338082  0.39351
 0.32363   0.334992  0.39283

In [8]:
println(sum(Wnormed, dims=1))

[1.0 1.0 0.9999999999999998]


In [9]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

In [11]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [12]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [13]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

In [14]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [15]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [16]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

In [17]:
v = rand(3)

3-element Vector{Float64}:
 0.15981857331292515
 0.34086080859766343
 0.18791058808128658

In [18]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.159819  0.340861  0.187911

In [19]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : Vector

{Vector{Float64}}
Size : (5,)


In [20]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : LinearAlgebra.Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


In [21]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [22]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)


In [23]:
p = 0.7
N = 100

100

In [24]:
using BenchmarkTools

In [25]:
@benchmark floor.(p .+ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.91 KiB
  allocs estimate:  7
  --------------
  minimum time:     871.739 ns (0.00% GC)
  median time:      904.348 ns (0.00% GC)
  mean time:        974.225 ns (2.56% GC)
  maximum time:     17.083 μs (89.20% GC)
  --------------
  samples:          10000
  evals/sample:     46

In [26]:
println(sum(floor.(p .+ rand(N)) .== 1.0) / N) 

0.64


In [27]:
@benchmark 1.0f0 * (p .≥ rand(N))

BenchmarkTools.Trial: 
  memory estimate:  1.55 KiB
  allocs estimate:  6
  --------------
  minimum time:     926.923 ns (0.00% GC)
  median time:      984.615 ns (0.00% GC)
  mean time:        1.073 μs (2.68% GC)
  maximum time:     34.273 μs (94.74% GC)
  --------------
  samples:          10000
  evals/sample:     26

In [28]:
println(sum(1.0f0 * (p .≥ rand(N)) .== 1.0) / N) 

0.73


In [29]:
using LinearAlgebra, Kronecker, Random

In [30]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [31]:
vec(X) = vcat(X...)

vec (generic function with 1 method)

In [32]:
X = reshape((B' ⊗ A)^-1 * vec(C), (m, m))

4×4 Matrix{Float64}:
  1.38465     0.268013    7.1421     5.77661
 -0.287663   -1.16915    -5.12843   -4.21355
 -0.346694    0.424721   -0.178399  -0.115307
 -0.0775896   0.0606874  -0.152408  -0.118808

In [33]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [34]:
foo(a,b) = sum(a) + b

foo (generic function with 1 method)

In [35]:
println(foo.(Ref([1,2]),[3,4,5]))
println(foo.(([1,2],), [3,4,5]))
println(foo.([[1,2]], [3,4,5]))

[6, 7, 8]
[6, 7, 8]


[6, 7, 8]


In [36]:
var"log(θ+μ)" = 10

10