In [1]:
using LinearAlgebra

In [2]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [3]:
A = []

Any[]

In [4]:
W = rand(3,3)

3×3 Matrix{Float64}:
 0.208063  0.593138  0.381483
 0.319687  0.351225  0.394025
 0.142155  0.120187  0.499655

In [5]:
Wnormed = W ./ sum(W, dims=1)

3×3 Matrix{Float64}:
 0.310586  0.557172  0.299164
 0.477212  0.329928  0.309
 0.212202  0.1129    0.391837

In [6]:
println(sum(Wnormed, dims=1))

[1.0 0.9999999999999999 1.0]


In [7]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [8]:
B = [4 5 6; 7 8 9]

2×3 Matrix{Int64}:
 4  5  6
 7  8  9

In [9]:
H1 = hcat(A,B)

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [10]:
H2 = [A B]

2×5 Matrix{Int64}:
 1  2  4  5  6
 3  4  7  8  9

In [11]:
H3 = [A, B]

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [4 5 6; 7 8 9]

In [12]:
V1 = vcat(A, B')

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [13]:
V2 = [A; B']

5×2 Matrix{Int64}:
 1  2
 3  4
 4  7
 5  8
 6  9

In [14]:
[V2 [A;B']]

5×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 4  7  4  7
 5  8  5  8
 6  9  6  9

In [15]:
v = rand(3)

3-element Vector{Float64}:
 0.08078390066519736
 0.21880164577595063
 0.38638066402308535

In [16]:
newaxis = [CartesianIndex()]
v1 = v[newaxis, :]

1×3 Matrix{Float64}:
 0.0807839  0.218802  0.386381

In [17]:
I

UniformScaling{Bool}
true*I

In [18]:
I(3)

3×3 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

In [19]:
A = rand(2,2)
b = rand(2)

2-element Vector{Float64}:
 0.6642499593758039
 0.8357523767362349

In [20]:
x = inv(A) * b

2-element Vector{Float64}:
 -0.5413347924076956
  1.368260994277419

In [21]:
x = A \ b

2-element Vector{Float64}:
 -0.5413347924076958
  1.3682609942774193

In [22]:
using LinearAlgebra, Kronecker, Random

In [23]:
m = 4
A = randn(m, m)
B = randn(m, m)
C = convert(Array{Float64}, reshape(1:16, (m, m)))

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [24]:
X = reshape((B' ⊗ A) \ vec(C), (m, m))

4×4 Matrix{Float64}:
   148.347  -74.8909  -392.707   133.712
   113.584  -44.518   -278.883    99.2009
 -1055.49   507.847   2751.61   -945.167
  -544.143  269.801   1432.13   -489.247

In [25]:
A * X * B

4×4 Matrix{Float64}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

In [26]:
B = rand(2, 2, 2)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.681655  0.487036
 0.513269  0.277588

[:, :, 2] =
 0.262146  0.991841
 0.966683  0.713706

In [27]:
import Base.Iterators: flatten
collect(flatten(B))

8-element Vector{Float64}:
 0.6816546797447299
 0.5132688758361276
 0.4870356238821668
 0.27758760252750925
 0.26214565051023875
 0.966683275932893
 0.9918412964721871
 0.713705675056993

In [28]:
B[:]

8-element Vector{Float64}:
 0.6816546797447299
 0.5132688758361276
 0.4870356238821668
 0.27758760252750925
 0.26214565051023875
 0.966683275932893
 0.9918412964721871
 0.713705675056993

In [29]:
a = rand(2,3,5)
b = reshape(a, (:, 5))

6×5 Matrix{Float64}:
 0.918377  0.403922  0.621976   0.53253   0.857224
 0.18758   0.804664  0.552209   0.434259  0.834326
 0.738768  0.261772  0.621643   0.310129  0.993374
 0.501559  0.313444  0.564713   0.935804  0.726968
 0.726934  0.272811  0.123096   0.104811  0.605749
 0.526304  0.912738  0.0609884  0.291267  0.487083

In [30]:
A1 = [i*rand(3) for i=1:5]

println("Type : ", typeof(A1))
println("Size : ", size(A1))

Type : Vector{Vector{Float64}}
Size : (5,)


In [31]:
A2 = hcat(A1...)'

println("Type : ", typeof(A2))
println("Size : ", size(A2))

Type : Adjoint{Float64, Matrix{Float64}}
Size : (5, 3)


In [32]:
B1 = [i*rand(3, 4, 5) for i=1:6]

println("Type : ", typeof(B1))
println("Size : ", size(B1))

Type : Vector{Array{Float64, 3}}
Size : (6,)


In [33]:
B2 = permutedims(cat(B1..., dims=4), [4, 1, 2, 3])

println("Type : ", typeof(B2))
println("Size : ", size(B2))

Type : Array{Float64, 4}
Size : (6, 3, 4, 5)
